"""
Generate a single telecom_init.sql file containing all DDL (CREATE TABLE)
and INSERT INTO statements needed to initialize DuckDB with the telecom NMS
schema and mock data.

The output SQL can be pasted into WrenAI's DuckDB "Initial SQL statements" field.

Usage:
    python -m telecom.build_init_sql
"""

from datetime import date, datetime
from pathlib import Path

import duckdb

from telecom.csv_to_ddl import TABLE_ORDER, generate_ddl

DEFAULT_DB_PATH = Path(__file__).resolve().parent.parent / "telecom_nms.duckdb"
DEFAULT_CSV_PATH = (
    Path(__file__).resolve().parent.parent / "WrenAI" / "nms_field_dictionary_full.csv"
)
DEFAULT_OUTPUT_PATH = Path(__file__).resolve().parent.parent / "telecom_init.sql"

BATCH_SIZE = 100


def _format_value(val) -> str:
    """Format a Python value as a SQL literal."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, datetime):
        return f"'{val.strftime('%Y-%m-%d %H:%M:%S')}'"
    if isinstance(val, date):
        return f"'{val.isoformat()}'"
    if isinstance(val, (int, float)):
        return str(val)
    # String: escape single quotes by doubling them
    escaped = str(val).replace("'", "''")
    return f"'{escaped}'"


def _generate_inserts(con, table_name: str) -> list[str]:
    """Generate INSERT INTO statements for a table, batching rows."""
    rows = con.execute(f"SELECT * FROM {table_name}").fetchall()
    if not rows:
        return []

    col_names = [desc[0] for desc in con.description]
    col_list = ", ".join(col_names)

    statements = []
    for i in range(0, len(rows), BATCH_SIZE):
        batch = rows[i : i + BATCH_SIZE]
        value_rows = []
        for row in batch:
            vals = ", ".join(_format_value(v) for v in row)
            value_rows.append(f"  ({vals})")
        values_sql = ",\n".join(value_rows)
        stmt = f"INSERT INTO {table_name} ({col_list}) VALUES\n{values_sql};"
        statements.append(stmt)

    return statements


def build_init_sql(
    db_path: str | None = None,
    csv_path: str | None = None,
    output_path: str | None = None,
) -> str:
    """Build the complete init SQL and write it to a file.

    Args:
        db_path: Path to an existing telecom_nms.duckdb file.
        csv_path: Path to the NMS field dictionary CSV (for DDL generation).
        output_path: Where to write the resulting SQL file.

    Returns:
        The path of the written SQL file.
    """
    db_path = str(db_path or DEFAULT_DB_PATH)
    csv_path = str(csv_path or DEFAULT_CSV_PATH)
    output_path = str(output_path or DEFAULT_OUTPUT_PATH)

    # 1. Generate DDL
    ddl_statements = generate_ddl(csv_path)

    # 2. Connect to existing DB and dump data as INSERT statements
    con = duckdb.connect(db_path, read_only=True)

    insert_blocks: list[str] = []
    for table_name in TABLE_ORDER:
        # Check if table exists in the DB
        exists = con.execute(
            "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = ?",
            [table_name],
        ).fetchone()[0]
        if not exists:
            continue
        inserts = _generate_inserts(con, table_name)
        if inserts:
            insert_blocks.append(f"-- Data for {table_name}")
            insert_blocks.extend(inserts)

    con.close()

    # 3. Assemble final SQL
    parts = [
        "-- ===========================================",
        "-- Telecom NMS Schema + Data Init SQL",
        "-- Generated by telecom.build_init_sql",
        "-- ===========================================",
        "",
        "-- DDL",
    ]
    parts.extend(ddl_statements)
    parts.append("")
    parts.append("-- DATA")
    parts.extend(insert_blocks)
    parts.append("")

    full_sql = "\n\n".join(parts)

    Path(output_path).write_text(full_sql, encoding="utf-8")
    print(f"Init SQL written to {output_path}")
    print(
        f"  DDL: {len(ddl_statements)} tables, "
        f"Data: {len(insert_blocks)} statement blocks"
    )
    return output_path


if __name__ == "__main__":
    build_init_sql()
